### ISSUE TITLE
Workflow restructuring for multi-architecture support

### ISSUE THREAD

**Issue by grief8** [asterinas/asterinas#1916]
## Problem Statement

Current CI workflows (`test_asterinas.yml`, `test_osdk.yml`) contain architecture-specific logic and general testing steps tightly coupled, making it difficult to:

1.  Add new architecture targets (ARM/RISC-V)
2.  Maintain consistent testing patterns across platforms
3.  Reuse common validation logic
4.  Isolate hardware-specific configurations

## Proposed Solution

The CI workflow has been restructured into two core components with improved separation of concerns:

1.  **Backend Integration Layer (`test_backend.yml`)**: Reusable workflow for core test logic:
    - Unified test execution for multiple architectures
    - Parameterized via 10+ inputs:
      - `auto_test`: Test type (boot, syscall, test, osdk, general)
      - `release`: Release build flag
      - `enable_kvm`: KVM acceleration
      - `intel_tdx`: Intel TDX support
      - `smp`: CPU core count
      - `netdev`: Network device type
      - `scheme`: Scheme corresponding to `Makefile` (e.g., iommu)
      - `extra_blocklists`: Custom blocklist paths
      - `syscall_test_dir`: Syscall test directory
      - `boot_protocol`: Boot protocol (e.g., multiboot, efi)
      - `runs_on`: Runner environment (e.g., ubuntu-latest, tdx-runner)
      - `timeout_minutes`: Test timeout duration
      - `container_image`: Test container images (JSON array)

    - Defines 3 jobs: `general-test`, `integration-test`, `osdk-test`
      - Independent job execution within backend workflow
      - Frontend workflows responsible for calling 
      - `general-test`: Architecture-independent tests, (e.g., Rustfmt and Clippy linting, Unit tests)
      - `integration-test`: Core test execution with flexible parameters
      - `osdk-test`: OSDK linting and unit tests using container matrix

2.  **Architecture Frontends**: Platform-specific test orchestration:
    - `test_x86.yml`: x86_64 workflow
      - Phase 1: General checks (lint, build, unit tests)
      - Phase 2: Matrix-based integration tests
        - Boot, syscall, general test types
        - KVM, memory scheme variations
      - Phase 3: OSDK linting and unit tests

    - `test_x86_tdx.yml`: Intel TDX workflow
      - Phase 1: Matrix-based integration tests
        - Boot, syscall, general test types
        - KVM, memory scheme variations
        - Enable TDX feature
      - Phase 2: OSDK linting and unit tests

    Example of how the frontends call the backend:

    ```yaml
    # test_x86.yml
    jobs:
      general-checks:
        uses: ./.github/workflows/backend_integration.yml
        with:
          container_image: 'asterinas/asterinas:0.14.0'
          runs_on: 'ubuntu-latest'
          auto_test: 'general'
          release: true
          enable_kvm: false
          intel_tdx: false

      x86-test:
        uses: ./.github/workflows/backend_integration.yml
        strategy:
          matrix:
            test_id:
              - 'boot_mb'
              - 'syscall_debug'
              # ... other tests ...
          fail-fast: false
        with:
          test_id: ${{ matrix.test_id }}
          auto_test: ${{ startsWith(matrix.test_id, 'boot') && 'boot' || ... }}
          # ... other parameters ...
    ```

### Key Changes

- Workflow input standardization (14+ parameters)
- YAML reduction: 68% config reuse via backend workflow
- Modular architecture: 3 core workflows with distinct roles

## Additional Considerations

1. Currently, the OSDK workflow (`test_osdk.yml`) is triggered only when specific files are modified.  However, combining these checks into a single frontend workflow (`test_x86.yml`) results in a trigger on every pull_request to the repository.
https://github.com/asterinas/asterinas/blob/3ef8f20de655e2f36dae53fb003ec36e751245d7/.github/workflows/test_osdk.yml#L4-L9

2. The general check is architecture-independent. It is better to place it in another file like `test_general.yml`, but we already have too many files. Maybe we should move it after we indeed introduce other architectures.
