### ISSUE TITLE
Build and push the Docker image in CI

### ISSUE THREAD

**Issue by junyang-zh** [asterinas/asterinas#368]
We could build and push the development Docker image when the Dockerfile is changed. Add a `.github/workflows/docker_build.yml` like this:

```yml
name: Docker image build

on:
  push:
    paths:
      - ./tools/docker/
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./tools/docker/Dockerfile.ubuntu22.04
          platforms: linux/x86_64
          build-args: JINUX_BRANCH=${{ env.JINUX_BRANCH }}
          push: true
          tags: jinuxdev/jinux:${{ env.IMAGE_TAG }}

```

@StevenJiang1110 maybe you can figure out how to pass the Dockerhub token?
