### ISSUE TITLE
Introducing a Mechanism to Rerun Failed GitHub Actions Workflow Jobs

### ISSUE THREAD

**Issue by grief8** [asterinas/asterinas#988]
## Background
In the Asterinas, we occasionally encounter situations where certain jobs fail during a Pull Request (PR), e.g., #977 . These failures can be due to various reasons. Currently, the common practice to address these failures is to re-push changes to the original branch, which forces all jobs to re-execute. However, this method is not elegant, as it results in the unnecessary re-execution of jobs that have already passed.

## Proposal
To address this issue, we propose the introduction of a new workflow that allows the PR owner to selectively rerun only the failed jobs. This workflow will be triggered by a comment on the PR containing a specific command `/rerun`, and it will use the GitHub API to identify and rerun the failed jobs without affecting the successful ones.

### Workflow Details

- **Name**: Rerun Failed Workflow
- **Trigger**: An issue comment containing the command `/rerun` on a pull request.
- **Actions**:
  1. Verify if the comment contains the `/rerun` command and is from a pull request.
  2. Identify the PR owner.
  3. Check if the comment author is the PR owner.
  4. Retrieve the IDs of all failed workflow runs associated with the PR.
  5. For each failed workflow run, identify the failed job IDs.
  6. Rerun each failed job using the GitHub API.

```yml
# .github/workflows/rerun-failed-workflow.yml
name: Rerun Failed Workflow

on:
  issue_comment:
    types: [created]

jobs:
  rerun-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check if comment contains rerun command and is from a pull request
        id: check_comment
        run: |
          echo "COMMENT_BODY=${{ github.event.comment.body }}" >> $GITHUB_ENV
          if [[ "${{ github.event.comment.body }}" == "/rerun" && "${{ github.event.issue.pull_request }}" ]]; then
            echo "RERUN_COMMAND=true" >> $GITHUB_ENV
          fi
          
      - name: Get pull request owner
        if: env.RERUN_COMMAND == 'true'
        id: get_pr_owner
        run: |
          PR_NUMBER=$(echo ${{ github.event.issue.number }})
          PR_OWNER=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" | \
            jq -r '.user.login')
          echo "PR_OWNER=$PR_OWNER" >> $GITHUB_ENV
          
      - name: Check if comment author is pull request owner
        if: env.RERUN_COMMAND == 'true'
        id: check_author
        run: |
          COMMENT_AUTHOR=$(echo ${{ github.event.comment.user.login }})
          if [[ "$COMMENT_AUTHOR" == "$PR_OWNER" ]]; then
            echo "AUTHOR_IS_OWNER=true" >> $GITHUB_ENV
          fi
          
      - name: Rerun failed jobs in all failed workflow runs
        if: env.RERUN_COMMAND == 'true' && env.AUTHOR_IS_OWNER == 'true'
        run: |
          # Debug: Print environment variables
          echo "RERUN_COMMAND: ${{ env.RERUN_COMMAND }}"
          echo "AUTHOR_IS_OWNER: ${{ env.AUTHOR_IS_OWNER }}"
          
          # Get the workflow run IDs of all failed runs
          WORKFLOW_RUN_IDS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs" | \
            jq -r '.workflow_runs[] | select(.status == "completed" and .conclusion == "failure") | .id')
          
          # Debug: Print workflow run IDs
          echo "Workflow Run IDs: $WORKFLOW_RUN_IDS"
          
          # Rerun each failed job in each failed workflow run
          for WORKFLOW_RUN_ID in $WORKFLOW_RUN_IDS; do
            # Get the jobs of the failed workflow run
            JOBS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/$WORKFLOW_RUN_ID/jobs")
            
            # Find the failed job IDs
            FAILED_JOB_IDS=$(echo $JOBS | jq -r '.jobs[] | select(.conclusion == "failure") | .id')
            
            # Debug: Print failed job IDs
            echo "Failed Job IDs for Workflow Run ID $WORKFLOW_RUN_ID: $FAILED_JOB_IDS"
            
            # Rerun each failed job
            for JOB_ID in $FAILED_JOB_IDS; do
              echo "Rerunning job ID: $JOB_ID"
              RESPONSE=$(curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                "https://api.github.com/repos/${{ github.repository }}/actions/jobs/$JOB_ID/rerun")
              
              echo "Failed to rerun job ID $JOB_ID. $RESPONSE"
            done
          done
```

### Open Questions

Although this workflow is simple and fast, it will lead to a series of actions in our action as follows:

![image](https://github.com/asterinas/asterinas/assets/24353687/6deab3ea-7f2b-4a3b-b0d5-0a84f11682d5)
